### ISSUE TITLE
Genres not updating with new songs

### ISSUE THREAD

**Issue by realKeehan** [LucasOe/spicetify-genres#1]
The listed genres do not update when the song is changed

**Comment by LucasOe** [comment]
I just published a new release, that fixed an issue that caused genres to not appear in the latest version of Spotify. Can you please test if this fixed your problem? Everything is working on my end.

**Comment by brusvv** [comment]
Spotify for Windows (32 bit)
1.2.37.701.ge66eb7bc
Spicetify v2.36.11
xpui_2024-05-03_1714757530304_e66eb7b
cef_122.1.13+gde5b724+chromium-122.0.6261.130
Runtime: Chrome
Build System: CMake

Doesn't work too.
