### ISSUE TITLE
Many genres overload view

### ISSUE THREAD

**Issue by lichenophile** [LucasOe/spicetify-genres#2]
![image](https://github.com/LucasOe/spicetify-genres/assets/67679349/afbba388-39d4-4863-9c35-4805f6f914d2)

Perhaps a auto-scrolling or scrollable field for this would work better for tracks that have many genres associated

**Comment by LucasOe** [comment]
Yes, that's a good suggestion. I will try looking into this when I have the time.

**Comment by LucasOe** [comment]
In version 1.3.0, I added a marquee effect for when the text overflows, which should address the issue with tracks that have many associated genres. Please test the latest release and let me know if you encounter any bugs or have further feedback.

**Comment by lichenophile** [comment]
Works well, thank you, the scroll speed is appreciated as the list can be long haha

I'm entirely happy with this implementation, feel free to close this request!

<details>
<summary><sup>but if you wanted to over-engineer this outta boredom or something...</sup></summary>
Spotify handles overflow scroll a little differently, and is somewhat overkill. However, it's approach is potentially less distracting than an infinite scroll. Especially with the speed the genres (imo) should rightly go at lol

Default spotify behaviour for track name and artist:

`Scenario A` 
An initial no-repeat auto-scroll with 'bounce' when playback begins.
**What happens:** 
The field slowly auto-scrolls, scrolling backward to the start then comes to rest
**Caveat:** 
If the user hovers the field during scroll it temporarily halts, resuming to complete the scroll when the mouse has left.
(Nice, but who knows if the user is even looking at/for this info specifically at track start)
 
 The fields do not scroll again, unless:
`Scenario B` 
A manually activated no-repeat 'bounce' scroll when user hovers the related field 
**What happens:** 
_Mostly_ the same as `Scenario A`, a single scroll that returns to it's point of origin via direction reversal
**Caveat 1:** 
This scroll continues to completion, _even if the mouse leaves the area_
**Caveat 2:** 
If the mouse leaves the fields and then hovers the same field again while the scroll is still incomplete, it temporarily halts, resuming to complete once the mouse has again left the area.

While it might be nice to implement both scenarios for a consistent appearance and feel, the slow speed might indeed decrease the user experience on longer genre lists... 

A simpler approach would be to do something similar to just the `B` scenario, using the extensions current speed.
Since this isn't aiming for a 'match spotify' feel, the 'bounce' scroll doesn't serve any important purpose either, but we have a very usable scroll that isn't always speeding along.
</details>

**Comment by LucasOe** [comment]
Thanks for the detailed feedback! I might take a look at one of these solutions, but generally I want to avoid over-engeneering it.
