### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by miloszastic6669** [LucasOe/spicetify-genres#3]
I'm not really familiar with js, but I'm pretty sure that there is an exposed API Key right at the beginning of [spotifyGenres.js](https://raw.githubusercontent.com/Vexcited/better-spotify-genres/build/spotifyGenres.js): 

`var e="44654...";`

**Comment by LucasOe** [comment]
The file you have linked isn't from this reposity, it is from [better-spotify-genres](https://github.com/Vexcited/better-spotify-genres).
