### ISSUE TITLE
why is TUYU's music called "Rhythm Game"

### ISSUE THREAD

**Issue by m1nhnhatreal** [LucasOe/spicetify-genres#5]
![image](https://github.com/user-attachments/assets/35ed8cc2-9aba-4189-b3be-c539af940821)
i think rhythm game music is the music that was use in rhythm game, not the music itself, i think TUYU's music its kind of rock or pop?

**Comment by LucasOe** [comment]
The genres are provided by Spotify, I don't have control over them.
